from models import Room
import time 

def get_mock_rooms():
    return {
        '000000001' : Room(id = '000000001',
        name= 'aristotle philosophy debate',
        tags= ['Education', 'Politics'],
        teams=False,
        team_names=[],
        room_size=5,
        time_to_start= time.time() + 1200,
        allow_spectators=True,
        users_list={},
        spectators_list={},
        moderator='',
        is_conversation=False,
        pictureId= 164336,
        blacklist=[],
        user_reports={}),
        
        '000000002' : Room(id = '000000002',
        name= 'Cola or Pepsi ?',
        tags= ['Health'],
        teams=True,
        team_names=['Cola', 'Pepsi'],
        room_size=6,
        time_to_start= time.time() + 900,
        allow_spectators=False,
        users_list={},
        spectators_list={},
        moderator='',
        is_conversation=False,
        pictureId= 700042,
        blacklist=[],
        user_reports={}),

        '000000003' : Room(id = '000000003',
        name= 'TAU or BGU?',
        tags= ['Education'],
        teams=False,
        team_names=[],
        room_size=8,
        time_to_start= time.time() + 60,
        allow_spectators=False,
        users_list={},
        spectators_list={},
        moderator='',
        is_conversation=False,
        pictureId= 4560148,
        blacklist=[],
        user_reports={}),

        '000000004' : Room(id = '000000004',
        name= 'best Marvel Movie ?!?!',
        tags= ['Culture'],
        teams=False,
        team_names=[],
        room_size=6,
        time_to_start= time.time() + 1600,
        allow_spectators=False,
        users_list={},
        spectators_list={},
        moderator='',
        is_conversation=False,
        pictureId= 7809122,
        blacklist=[],
        user_reports={}),

        '000000005' : Room(id = '000000005',
        name= 'Climate change responsibility',
        tags= ['Climate change', 'Politics'],
        teams=True,
        team_names=['humans', 'nature'],
        room_size=7,
        time_to_start= time.time() + 360,
        allow_spectators=True,
        users_list={},
        spectators_list={},
        moderator='',
        is_conversation=False,
        pictureId= 1072824,
        blacklist=[],
        user_reports={}),

        '000000006' : Room(id = '000000006',
        name= 'Goat debate: Messi or Ronaldo ?',
        tags= ['Sports', 'Culture'],
        teams=True,
        team_names=['Messi', 'Ronaldo'],
        room_size=9,
        time_to_start= time.time() + 2400,
        allow_spectators=True,
        users_list={},
        spectators_list={},
        moderator='',
        is_conversation=False,
        pictureId= 1884574,
        blacklist=[],
        user_reports={}),

        '000000007' : Room(id = '000000007',
        name= 'math vs physics',
        tags= ['Sceince'],
        teams=True,
        team_names=['math', 'physics'],
        room_size=3,
        time_to_start= time.time() + 300,
        allow_spectators=True,
        users_list={},
        spectators_list={},
        moderator='',
        is_conversation=False,
        pictureId= 5212320,
        blacklist=[],
        user_reports={})
    }